# Generated by Django 4.0.4 on 2022-05-20 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=20, verbose_name='Nombres')),
                ('dni', models.IntegerField(max_length=20, unique=True, verbose_name='DNI')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
