# Generated by Django 4.0.4 on 2022-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='DNI'),
        ),
    ]
