# Generated by Django 4.0.4 on 2022-05-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_models', '0003_type_employee_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table='Tipo de Empleado',
        ),
    ]
