# Generated by Django 4.0.4 on 2022-05-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_models', '0004_alter_type_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table='empleado_tipos',
        ),
    ]
