# Generated by Django 4.0.4 on 2022-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_models', '0005_alter_type_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='categ',
            field=models.ManyToManyField(to='erp_models.category'),
        ),
    ]
